In [1]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv('players.csv')

In [32]:
print(df)

    player_id      name position  age            team  games_played  minutes  \
0           1   Adeyemi       PG   24  Lagos Leopards            28      896
1           2    Okafor       SG   29  Lagos Leopards            30      960
2           3   Balogun       SF   26  Lagos Leopards            27      864
3           4    Diallo       PF   31  Lagos Leopards            29      928
4           5     Nwosu        C   28  Lagos Leopards            30      900
5           6     Owusu       PG   22      Accra Aces            25      700
6           7    Appiah       SG   27      Accra Aces            28      868
7           8   Danquah       SF   25      Accra Aces            26      780
8           9     Bello       PF   30      Accra Aces            29      870
9          10    Chukwu        C   33      Accra Aces            27      756
10         11      Eneh       PG   23      Kano Kings            24      672
11         12    Gyamfi       SG   26      Kano Kings            29      870
12         13    Hassan       SF   28      Kano Kings            30      930
13         14    Ikpeba       PF   24      Kano Kings            22      660
14         15    Jalloh        C   31      Kano Kings            28      812
15         16    Kamara       PG   20   Abuja Pythons            18      486
16         17     Lawal       SG   25   Abuja Pythons            27      810
17         18  Mohammed       SF   29   Abuja Pythons            29      870
18         19   Nkrumah       PF   27   Abuja Pythons            26      780
19         20     Oduya        C   32   Abuja Pythons            30      870
20         21    Peprah       PG   26   Kumasi Giants            19      342
21         22   Quansah       SG   21   Kumasi Giants            15      240
22         23    Rahman       SF   33   Kumasi Giants            11      154
23         24     Sowah       PF   28   Kumasi Giants            22      374
24         25    Tetteh        C   30   Kumasi Giants            24      384

    points  assists  personal_fouls  technical_fouls
0      336      196              58                0
1      540      120              64                1
2      410      140              70                0
3      380       60             112                2
4      340       40             128                1
5      245      175              45                0
6      460       90              58                0
7      360      110              66                0
8      330       55             118                3
9      260       35             130                1
10     230      168              42                0
11     470       95              60                0
12     420      120              74                1
13     255       48              95                2
14     290       30             120                2
15     160      120              30                0
16     430       80              52                0
17     395      105              68                0
18     300       50             105                1
19     315       32             132                1
20     120       90              22                0
21     120       30              16                0
22      60       18              14                0
23     150       25              55                0
24     140       15              60                1

Exploratory Data Analysis

In [9]:
df.shape

(25, 11)

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   player_id        25 non-null     int64
 1   name             25 non-null     str
 2   position         25 non-null     str
 3   age              25 non-null     int64
 4   team             25 non-null     str
 5   games_played     25 non-null     int64
 6   minutes          25 non-null     int64
 7   points           25 non-null     int64
 8   assists          25 non-null     int64
 9   personal_fouls   25 non-null     int64
 10  technical_fouls  25 non-null     int64
dtypes: int64(8), str(3)
memory usage: 2.8 KB

In [11]:
df.describe()

,player_id,age,games_played,minutes,points,assists,personal_fouls,technical_fouls
count,25.000000,25.000000,25.000000,25.000000,25.000000,25.00000,25.000000,25.000000
mean,13.000000,27.120000,25.320000,711.040000,300.640000,81.88000,71.760000,0.640000
std,7.359801,3.609247,5.014313,237.288938,125.877877,52.22493,36.298852,0.860233
min,1.000000,20.000000,11.000000,154.000000,60.000000,15.00000,14.000000,0.000000
25%,7.000000,25.000000,24.000000,660.000000,230.000000,35.00000,52.000000,0.000000
50%,13.000000,27.000000,27.000000,810.000000,315.000000,80.00000,64.000000,0.000000
75%,19.000000,30.000000,29.000000,870.000000,395.000000,120.00000,105.000000,1.000000
max,25.000000,33.000000,30.000000,960.000000,540.000000,196.00000,132.000000,3.000000

In [14]:
df.head(8)

,player_id,name,position,age,team,games_played,minutes,points,assists,personal_fouls,technical_fouls
0,1,Adeyemi,PG,24,Lagos Leopards,28,896,336,196,58,0
1,2,Okafor,SG,29,Lagos Leopards,30,960,540,120,64,1
2,3,Balogun,SF,26,Lagos Leopards,27,864,410,140,70,0
3,4,Diallo,PF,31,Lagos Leopards,29,928,380,60,112,2
4,5,Nwosu,C,28,Lagos Leopards,30,900,340,40,128,1
5,6,Owusu,PG,22,Accra Aces,25,700,245,175,45,0
6,7,Appiah,SG,27,Accra Aces,28,868,460,90,58,0
7,8,Danquah,SF,25,Accra Aces,26,780,360,110,66,0

In [15]:
df.tail()

,player_id,name,position,age,team,games_played,minutes,points,assists,personal_fouls,technical_fouls
20,21,Peprah,PG,26,Kumasi Giants,19,342,120,90,22,0
21,22,Quansah,SG,21,Kumasi Giants,15,240,120,30,16,0
22,23,Rahman,SF,33,Kumasi Giants,11,154,60,18,14,0
23,24,Sowah,PF,28,Kumasi Giants,22,374,150,25,55,0
24,25,Tetteh,C,30,Kumasi Giants,24,384,140,15,60,1

In [17]:
print (df.columns)

Index(['player_id', 'name', 'position', 'age', 'team', 'games_played',
       'minutes', 'points', 'assists', 'personal_fouls', 'technical_fouls'],
      dtype='str')

In [20]:
#print (df.iloc[2])
print (df.iloc[0:5])

   player_id     name position  age            team  games_played  minutes  \
0          1  Adeyemi       PG   24  Lagos Leopards            28      896
1          2   Okafor       SG   29  Lagos Leopards            30      960
2          3  Balogun       SF   26  Lagos Leopards            27      864
3          4   Diallo       PF   31  Lagos Leopards            29      928
4          5    Nwosu        C   28  Lagos Leopards            30      900

   points  assists  personal_fouls  technical_fouls
0     336      196              58                0
1     540      120              64                1
2     410      140              70                0
3     380       60             112                2
4     340       40             128                1

In [23]:
print (df.loc[df['name'] == 'Diallo'])

   player_id    name position  age            team  games_played  minutes  \
3          4  Diallo       PF   31  Lagos Leopards            29      928

   points  assists  personal_fouls  technical_fouls
3     380       60             112                2

In [30]:
print (df.loc[df['team'] == 'Lagos Leopards'])

   player_id     name position  age            team  games_played  minutes  \
0          1  Adeyemi       PG   24  Lagos Leopards            28      896
1          2   Okafor       SG   29  Lagos Leopards            30      960
2          3  Balogun       SF   26  Lagos Leopards            27      864
3          4   Diallo       PF   31  Lagos Leopards            29      928
4          5    Nwosu        C   28  Lagos Leopards            30      900

   points  assists  personal_fouls  technical_fouls
0     336      196              58                0
1     540      120              64                1
2     410      140              70                0
3     380       60             112                2
4     340       40             128                1

In [41]:
guards = df[df['position'].isin(['SG', 'PG'])]
print(guards.shape)
print (guards.head(10))

(10, 11)
    player_id     name position  age            team  games_played  minutes  \
0           1  Adeyemi       PG   24  Lagos Leopards            28      896
1           2   Okafor       SG   29  Lagos Leopards            30      960
5           6    Owusu       PG   22      Accra Aces            25      700
6           7   Appiah       SG   27      Accra Aces            28      868
10         11     Eneh       PG   23      Kano Kings            24      672
11         12   Gyamfi       SG   26      Kano Kings            29      870
15         16   Kamara       PG   20   Abuja Pythons            18      486
16         17    Lawal       SG   25   Abuja Pythons            27      810
20         21   Peprah       PG   26   Kumasi Giants            19      342
21         22  Quansah       SG   21   Kumasi Giants            15      240

    points  assists  personal_fouls  technical_fouls
0      336      196              58                0
1      540      120              64                1
5      245      175              45                0
6      460       90              58                0
10     230      168              42                0
11     470       95              60                0
15     160      120              30                0
16     430       80              52                0
20     120       90              22                0
21     120       30              16                0

In [44]:
df['points_plus_assists'] = df['points'] + df['assists']
df['points_per_game'] = df['points'] / (df['games_played'] / 36)

In [46]:
print (df.head())

   player_id     name position  age            team  games_played  minutes  \
0          1  Adeyemi       PG   24  Lagos Leopards            28      896
1          2   Okafor       SG   29  Lagos Leopards            30      960
2          3  Balogun       SF   26  Lagos Leopards            27      864
3          4   Diallo       PF   31  Lagos Leopards            29      928
4          5    Nwosu        C   28  Lagos Leopards            30      900

   points  assists  personal_fouls  technical_fouls  points_plus_assists  \
0     336      196              58                0                  532
1     540      120              64                1                  660
2     410      140              70                0                  550
3     380       60             112                2                  440
4     340       40             128                1                  380

   points_per_game
0       432.000000
1       648.000000
2       546.666667
3       471.724138
4       408.000000

In [47]:
conditions=[
    (df['position'] == 'PG'),
    (df['position'] == 'SG'), 
    (df['position'] == 'SF'),
    (df['position'] == 'PF'),
    (df['position'] == 'C')
]
choices = ['Point Guard', 'Shooting Guard', 'Small Forward', 'Power Forward', 'Center']
df['position_full'] = np.select(conditions, choices, default='Unknown')

print(df[['name', 'position', 'position_full']].head())

      name position   position_full
0  Adeyemi       PG     Point Guard
1   Okafor       SG  Shooting Guard
2  Balogun       SF   Small Forward
3   Diallo       PF   Power Forward
4    Nwosu        C          Center

In [48]:
df.to_csv('players_updated.csv', index=False)
print("Updated CSV file saved as 'players_updated.csv'")

Updated CSV file saved as 'players_updated.csv'

In [51]:
df1 = pd.read_csv('players_updated.csv')
df1.tail()

,player_id,name,position,age,team,games_played,minutes,points,assists,personal_fouls,technical_fouls,points_plus_assists,points_per_game,position_full
20,21,Peprah,PG,26,Kumasi Giants,19,342,120,90,22,0,210,227.368421,Point Guard
21,22,Quansah,SG,21,Kumasi Giants,15,240,120,30,16,0,150,288.000000,Shooting Guard
22,23,Rahman,SF,33,Kumasi Giants,11,154,60,18,14,0,78,196.363636,Small Forward
23,24,Sowah,PF,28,Kumasi Giants,22,374,150,25,55,0,175,245.454545,Power Forward
24,25,Tetteh,C,30,Kumasi Giants,24,384,140,15,60,1,155,210.000000,Center